import { ScrollView, Text, FlatList } from "react-native";

const DATA = [
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSIA",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
  "Halo BSI",
];
function BasicFlatlist() {
  return (
    <FlatList
      data={DATA}
      keyExtractor={(item) => item}
      renderItem={({ item }) => <Text>{item}</Text>}
    />
  );
}

export default BasicFlatlist;
